set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]

# Clock
set_property PACKAGE_PIN W5 [get_ports clk_i]
set_property IOSTANDARD LVCMOS33 [get_ports clk_i]
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports clk_i]

# Reset (BTND)
set_property PACKAGE_PIN U17 [get_ports rstn_i]
set_property IOSTANDARD LVCMOS33 [get_ports rstn_i]

# Switches (SW0-SW7: LVCMOS33; SW8-SW15: LVCMOS18)
set_property PACKAGE_PIN V17 [get_ports {sw_i[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_i[0]}]
set_property PACKAGE_PIN V16 [get_ports {sw_i[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_i[1]}]
set_property PACKAGE_PIN W16 [get_ports {sw_i[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_i[2]}]
set_property PACKAGE_PIN W17 [get_ports {sw_i[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_i[3]}]
set_property PACKAGE_PIN W15 [get_ports {sw_i[4]}]
set_Property IOSTANDARD LVCMOS33 [get_ports {sw_i[4]}]
set_property PACKAGE_PIN V15 [get_ports {sw_i[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_i[5]}]
set_property PACKAGE_PIN W14 [get_ports {sw_i[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_i[6]}]
set_property PACKAGE_PIN W13 [get_ports {sw_i[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_i[7]}]
set_property PACKAGE_PIN V2 [get_ports {sw_i[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {sw_i[8]}]
set_property PACKAGE_PIN T3 [get_ports {sw_i[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {sw_i[9]}]
set_property PACKAGE_PIN T2 [get_ports {sw_i[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {sw_i[10]}]
set_property PACKAGE_PIN R3 [get_ports {sw_i[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {sw_i[11]}]
set_property PACKAGE_PIN W2 [get_ports {sw_i[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {sw_i[12]}]
set_property PACKAGE_PIN U1 [get_ports {sw_i[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {sw_i[13]}]
set_property PACKAGE_PIN T1 [get_ports {sw_i[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {sw_i[14]}]
set_property PACKAGE_PIN R2 [get_ports {sw_i[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {sw_i[15]}]

# LEDs
set_property PACKAGE_PIN U16 [get_ports {led_o[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[0]}]
set_property PACKAGE_PIN E19 [get_ports {led_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[1]}]
set_property PACKAGE_PIN U19 [get_ports {led_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[2]}]
set_property PACKAGE_PIN V19 [get_ports {led_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[3]}]
set_property PACKAGE_PIN W18 [get_ports {led_o[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[4]}]
set_property PACKAGE_PIN U15 [get_ports {led_o[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[5]}]
set_property PACKAGE_PIN U14 [get_ports {led_o[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[6]}]
set_property PACKAGE_PIN V14 [get_ports {led_o[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[7]}]
set_property PACKAGE_PIN V13 [get_ports {led_o[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[8]}]
set_property PACKAGE_PIN V3 [get_ports {led_o[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[9]}]
set_property PACKAGE_PIN W3 [get_ports {led_o[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[10]}]
set_property PACKAGE_PIN U3 [get_ports {led_o[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[11]}]
set_property PACKAGE_PIN P3 [get_ports {led_o[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[12]}]
set_property PACKAGE_PIN N3 [get_ports {led_o[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[13]}]
set_property PACKAGE_PIN P1 [get_ports {led_o[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[14]}]
set_property PACKAGE_PIN L1 [get_ports {led_o[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[15]}]

# 7-segment display segments (including decimal point)
set_property PACKAGE_PIN W7 [get_ports {disp_seg_o[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {disp_seg_o[0]}]
set_property PACKAGE_PIN W6 [get_ports {disp_seg_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {disp_seg_o[1]}]
set_property PACKAGE_PIN U8 [get_ports {disp_seg_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {disp_seg_o[2]}]
set_property PACKAGE_PIN V8 [get_ports {disp_seg_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {disp_seg_o[3]}]
set_property PACKAGE_PIN U5 [get_ports {disp_seg_o[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {disp_seg_o[4]}]
set_property PACKAGE_PIN V5 [get_ports {disp_seg_o[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {disp_seg_o[5]}]
set_property PACKAGE_PIN U7 [get_ports {disp_seg_o[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {disp_seg_o[6]}]
set_property PACKAGE_PIN V7 [get_ports {disp_seg_o[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {disp_seg_o[7]}]

# 7-segment display digit enables (only 4 digits on Basys 3)
set_property PACKAGE_PIN U2 [get_ports {disp_an_o[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {disp_an_o[0]}]
set_property PACKAGE_PIN U4 [get_ports {disp_an_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {disp_an_o[1]}]
set_property PACKAGE_PIN V4 [get_ports {disp_an_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {disp_an_o[2]}]
set_property PACKAGE_PIN W4 [get_ports {disp_an_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {disp_an_o[3]}]

# Buttons
set_property PACKAGE_PIN T18 [get_ports {btnu_i}]  # BTNU (push/write)
set_property IOSTANDARD LVCMOS33 [get_ports {btnu_i}]
set_property PACKAGE_PIN U18 [get_ports {btnc_i}]  # BTNC (pop/read)
set_property IOSTANDARD LVCMOS33 [get_ports {btnc_i}]
